# Nome do site
site_name: "Poker Stats"

# Descrição
site_description: "Repositório de documentos de Requisitos de Software"
repo_name: "REQ-2025.2-T02-PokerStats"
repo_url: "https://github.com/mdsreq-fga-unb/REQ-2025.2-T02-PokerStats"

markdown_extensions:
  - admonition
  - pymdownx.details

# Configura a navegação do site
nav:
  - Início: index.md
  - Guia de Contribuição: GuiaDeContribuicao.md
  - Visão do Produto e Projeto: 
      - Cenário Atual do Cliente e do Negócio: unidade1/cenarioAtual.md
      - Solução Proposta: unidade1/solucaoProposta.md
      - Estratégias de Engenharia de Software: unidade1/estrategiaES.md
      - Engenharia de Requisitos: unidade2/EngenhariaDeRequisitos.md
      - Cronograma e Entregas: unidade1/cronogramaEntregas.md
      - Interação entre Equipe e Cliente: unidade1/interacaoEquipeCliente.md
      - REQUISITOS DE SOFTWARE: unidade2/REQUISITOS_DE_SOFTWARE.md
      - DoR&DoD: unidade2/DoR&DoD.md
      - Backlog: unidade2/Backlog.md
  - Estudo de Caso:
      - Estudo de caso PBB: unidade3/PBB.md
      - Estudo de caso USM: unidade3/USM.md
      - Estudo de caso DCU: unidade3/DCU.md
      - Manter Perfil do Paciente: unidade3/ManterPerfildoPaciente.md
      - Buscar Serviços de Saúde: unidade3/BuscarServicosdeSaude.md
      - Monitorar Desempenho do Sistema: unidade3/MonitorarDesempenhoDoSistema.md
      - Agendar Consulta: unidade3/CasoUsoAgendarConsulta
      - Gerenciar Campanha: unidade3/GerenciarCampanha.md
  - Lições Aprendidas:
      - Unidade 1: unidade1/licoesAprendidas.md
      - Unidade 2: unidade2/licoesAprendidas.md
      - unidade 3: unidade3/licoesAprendidas.md
  - Evidencias: Evidencias/Evidencias.md
  - Entregas:
    - Unidade 1: entregas/videoApresentacao.md
    - Unidade 2: entregas/videoApresentacao2.md
    - Unidade 3: entregas/videoApresentacao3.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo claro

  language: pt-BR
  favicon: 
  logo: 

extra:
  version:
    provider: felipe

extra_css: [stylesheets/extra.css]