name: Build Windows Exe (Dev)

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      shell: pwsh
      run: |
        $CTK_INFO = pip show customtkinter
        $CTK_LOC = ($CTK_INFO | Select-String "Location:").ToString().Split(": ")[1].Trim()
        $CTK_PATH = Join-Path $CTK_LOC "customtkinter"

        echo "CustomTkinter encontrado em: $CTK_PATH"

        $MATP_INFO = pip show matplotlib
        $MATP_LOC = ($MATP_INFO | Select-String "Location:").ToString().Split(": ")[1].Trim()
        $MATP_DATA = Join-Path $MATP_LOC "matplotlib\mpl-data"

        echo "Matplotlib data encontrado em: $MATP_DATA"

        pyinstaller --noconfirm --onefile --windowed --name "PokerStats" `
          --hidden-import matplotlib `
          --hidden-import matplotlib.backends.backend_tkagg `
          --hidden-import matplotlib.backends.backend_agg `
          --hidden-import matplotlib.pyplot `
          --hidden-import matplotlib.figure `
          --hidden-import matplotlib.dates `
          --add-data "$CTK_PATH;customtkinter/" `
          --add-data "$MATP_DATA;matplotlib/mpl-data" `
          main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PokerStats-Windows-Dev
        path: dist/PokerStats.exe
